CREATE TABLE `data_platform_station_header_data`
(
  `Station`                          int(16) NOT NULL,
  `StationType`                      varchar(4) NOT NULL,
  `StationOwner`                     int(12) NOT NULL,
  `StationOwnerBusinessPartnerRole`  varchar(40) NOT NULL,
  `PrimaryLine`                      int(16) NOT NULL,
  `PersonResponsible`                varchar(40) DEFAULT NULL,
  `URL`                              varchar(200) DEFAULT NULL,
  `ValidityStartDate`                date NOT NULL,
  `ValidityEndDate`                  date NOT NULL,
  `DailyOperationStartTime           time NOT NULL,
  `DailyOperationEndTime`            time NOT NULL,
  `Description`                      varchar(60) NOT NULL,
  `LongText`                         varchar(1000) NOT NULL,
  `Introduction`                     varchar(200) DEFAULT NULL,
  `OperationRemarks`                 varchar(100) DEFAULT NULL,
  `PhoneNumber`                      varchar(40) DEFAULT NULL,
  `AvailabilityOfParking`            tinyint(1) DEFAULT NULL,
  `NumberOfParkingSpaces`            int(4) DEFAULT NULL,
  `Site`                             int(16) DEFAULT NULL,
  `SiteType`                         varchar(4) DEFAULT NULL,
  `Airport`                          int(16) DEFAULT NULL,
  `Project`                          int(16) DEFAULT NULL,
  `WBSElement`                       int(8) DEFAULT NULL,
  `Tag1`                             varchar(40) DEFAULT NULL,
  `Tag2`                             varchar(40) DEFAULT NULL,
  `Tag3`                             varchar(40) DEFAULT NULL,
  `Tag4`                             varchar(40) DEFAULT NULL,
  `CreationDate`                     date NOT NULL,
  `CreationTime`                     time NOT NULL,
  `LastChangeDate`                   date NOT NULL,
  `LastChangeTime`                   time NOT NULL,
  `CreateUser`                       int(12) NOT NULL,
  `LastChangeUser`                   int(12) NOT NULL,
  `IsReleased`                       tinyint(1) DEFAULT NULL,
  `IsMarkedForDeletion`              tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`Station`),

    CONSTRAINT `DPFMStationHeaderDataStationType_fk` FOREIGN KEY (`StationType`) REFERENCES `data_platform_station_type_station_type_data` (`StationType`),
    CONSTRAINT `DPFMStationHeaderDataStationOwner_fk` FOREIGN KEY (`StationOwner`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DPFMStationHeaderDataStationOwnerBPRole_fk` FOREIGN KEY (`StationOwnerBusinessPartnerRole`) REFERENCES `data_platform_bp_role_bp_role_data` (`BusinessPartnerRole`),
    CONSTRAINT `DPFMStationHeaderDataPrimaryLine_fk` FOREIGN KEY (`PrimaryLine`) REFERENCES `data_platform_railway_line_header_data` (`RailwayLine`),
    CONSTRAINT `DPFMStationHeaderDataSite_fk` FOREIGN KEY (`Site`) REFERENCES `data_platform_site_header_data` (`Site`),
    CONSTRAINT `DPFMStationHeaderDataSiteType_fk` FOREIGN KEY (`SiteType`) REFERENCES `data_platform_site_type_site_type_data` (`SiteType`),
    CONSTRAINT `DPFMStationHeaderDataAirport_fk` FOREIGN KEY (`Airport`) REFERENCES `data_platform_airport_header_data` (`Airport`),
    CONSTRAINT `DPFMStationHeaderDataProject_fk` FOREIGN KEY (`Project`) REFERENCES `data_platform_project_project_data` (`Project`),
    CONSTRAINT `DPFMStationHeaderDataWBSElement_fk` FOREIGN KEY (`Project`, `WBSElement`) REFERENCES `data_platform_project_wbs_element_data` (`Project`, `WBSElement`),
    CONSTRAINT `DPFMStationHeaderDataCreateUser_fk` FOREIGN KEY (`CreateUser`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DPFMStationHeaderDataLastChangeUser_fk` FOREIGN KEY (`LastChangeUser`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
